FROM arm32v7/ubuntu:20.04
# @todo test me
# https://github.com/hpool-dev/chia-miner/releases


WORKDIR /app
# Install prerequisites

COPY arm-release/hpool-miner-chia-linux-arm . 

CMD ["/app/hpool-miner-chia-linux-arm"]
