name: docker-build-push-pipe
on:
  push:
    paths:
      - "chia-miner-releases"
  workflow_dispatch:
jobs:
  build-and-push-arm-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release version
        run: echo "LATEST_ARM_RELEASE_VERSION=$(curl -sL https://api.github.com/repos/hpool-dev/chia-miner/releases/latest | jq -r '.tag_name')" >> $GITHUB_ENV
      - name: Get Release Url
        run: echo "LATEST_ARM_RELEASE_URL=$(curl -sL https://api.github.com/repos/hpool-dev/chia-miner/releases/latest |  jq -r '.assets|.[] |.browser_download_url' |grep linux)" >> $GITHUB_ENV
      - name: output software version
        run: echo $LATEST_ARM_RELEASE_URL version is  $LATEST_ARM_RELEASE_VERSION
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O release.zip $LATEST_ARM_RELEASE_URL
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -j -qq ./release.zip  -d ./arm-release
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ARM64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          file: Dockerfile.ARM
          push: true
          tags: schmiddim/hpool-miner-arm:${{ env.LATEST_ARM_RELEASE_VERSION}}
