#@see https://stackoverflow.com/a/58468828
name: Get latest release version
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/hpool-dev/chia-miner/releases/latest | \
          jq -r " .assets|.[] |.browser_download_url" |grep linux > chia-miner-releases
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Michael Schmitt'
          git config --global user.email 'schmiddim@users.noreply.github.com'
          git commit -am "New release version"
          git push
